---
# tasks file for nginx
#- name: Install Nginx
#  apt: name=nginx
#  become: yes

- name: Install Epel Release when CentOS or RedHat
  become: yes
  command: yum install epel-release -y
  when: (ansible_facts['distribution'] == "CentOS") or
        (ansible_facts['distribution'] == "RedHat") or 
        (ansible_facts['distribution'] == "Amazon")

- name: Install Nginx
  action: >
    {{ ansible_pkg_mgr }} name=nginx state=present update_cache=yes
  become: yes

#- name: write the Nginx config file
#  template: src=~/ansible-rails/roles/nginx/nginx_default dest=/etc/nginx/sites-available/default  
#  become: yes
#  notify:
#  - restart Nginx
- name: ensure Nginx is running (and enable it at boot)
  service: name=nginx state=started enabled=yes
  become: yes
