---
# tasks file for dependencies
- name: Install NodeJS
  apt: name=nodejs
  become: yes

- name: Install Postgres & Dependencies
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - postgresql
    - postgresql-contrib	
    - libpq-dev

- name: display post install message
  debug:
    msg:
      - 'Things left to do:'
      - 'RUN THE COMMANDS BELOW:'
      - 'ruby -v && rails -v'
      - 'source ~/.rvm/scripts/rvm'
      - 'ruby -v && rails -v'
