---
# tasks file for dependencies
- name: Install NodeJS
  apt: name=nodejs
  become: yes

- name: display post install message
  debug:
    msg:
      - 'THINGS LEFT TO DO:'
      - 'RUN THE COMMANDS BELOW:'
      - 'ruby -v && rails -v'
      - 'source ~/.rvm/scripts/rvm'
      - 'ruby -v && rails -v'
