---
# tasks file for ruby
#- name: Pull Key from gpg Server
#  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- name: Install Curl, Ruby and Rails - Sudo Style
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - curl
    - ruby
    - ruby-railties
- name: Get RVM URL
  get_url:
    url: https://get.rvm.io
    dest: ~/.rvm/scripts/rvm
- name: source RVM - Test
  shell: source {{ ansible_env.HOME }}/.rvm/scripts/rvm && rvm install ruby
  args:
    executable: /bin/bash
  register: source
- debug: var=source.stdout_lines

- name: curl rvm
  shell: curl -sSL https://get.rvm.io | bash 
- name: Source rvm script&Install Bundler&Rails
  shell: source ~/.rvm/scripts/rvm  && rvm install ruby && gem install bundler --no-ri --no-rdoc && gem install rails --no-ri --no-rdoc
  args:
    executable: /bin/bash
