---
# tasks file for ruby
#- name: Pull Key from gpg Server
#  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- name: Install Curl, Ruby and Rails - Sudo Style
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - curl
    - ruby
    - ruby-railties
    - ruby-bundler
- name: curl rvm
  ignore_errors: True
  shell: curl -sSL https://get.rvm.io | bash 

- name: Source rvm script&Install Bundler&Rails
  shell: source {{ ansible_env.HOME }}/.rvm/scripts/rvm  && rvm install ruby && gem install bundler --no-ri --no-rdoc && gem install rails --no-ri --no-rdoc
  register: source
  args:
    executable: /bin/bash
- debug: var=source.stdout_lines
